#!/bin/bash
# Policy Engine Setup Script for AgentCore Data Governance
#
# This script creates and configures the AgentCore Policy Engine with
# Cedar policies for governance operations.
#
# Requirements: 15.1, 15.4
# - Create policy engine with ENFORCE mode
# - Add Cedar policies to engine
#
# Usage:
#   ./scripts/setup_policy_engine.sh [--enforcement-mode ENFORCE|PERMISSIVE]
#
# Environment Variables:
#   AWS_REGION: AWS region for AgentCore (default: us-west-2)
#   GOVERNANCE_GATEWAY_ARN: ARN of the governance gateway

set -e

# Default configuration
DEFAULT_REGION="${AWS_REGION:-us-west-2}"
ENGINE_NAME="governance-policy-engine"
ENFORCEMENT_MODE="${1:-ENFORCE}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
POLICY_FILE="$PROJECT_ROOT/policies/governance_policies.cedar"
LOG_GROUP="/agentcore/policy-engine/governance"

echo "=============================================="
echo "AgentCore Policy Engine Setup"
echo "=============================================="
echo "Engine Name: $ENGINE_NAME"
echo "Enforcement Mode: $ENFORCEMENT_MODE"
echo "Region: $DEFAULT_REGION"
echo "Policy File: $POLICY_FILE"
echo "=============================================="

# Check if policy file exists
if [ ! -f "$POLICY_FILE" ]; then
    echo "Error: Policy file not found: $POLICY_FILE"
    exit 1
fi

# Check if agentcore CLI is available
if ! command -v agentcore &> /dev/null; then
    echo ""
    echo "Warning: AgentCore CLI not found."
    echo ""
    echo "=== Manual Setup Instructions ==="
    echo ""
    echo "1. Create Policy Engine:"
    echo "   aws bedrock-agentcore-control create-policy-engine \\"
    echo "     --name $ENGINE_NAME \\"
    echo "     --enforcement-mode $ENFORCEMENT_MODE"
    echo ""
    echo "2. Add Cedar Policies:"
    echo "   aws bedrock-agentcore-control add-policy \\"
    echo "     --policy-engine-name $ENGINE_NAME \\"
    echo "     --policy-file file://$POLICY_FILE"
    echo ""
    echo "3. Configure CloudWatch Logging:"
    echo "   aws bedrock-agentcore-control configure-policy-logging \\"
    echo "     --policy-engine-name $ENGINE_NAME \\"
    echo "     --log-group $LOG_GROUP"
    echo ""
    exit 1
fi

echo ""
echo "=== Step 1: Creating Policy Engine ==="
echo ""

# Create policy engine
ENGINE_ARN=$(agentcore policy create-engine \
    --name "$ENGINE_NAME" \
    --enforcement-mode "$ENFORCEMENT_MODE" \
    --region "$DEFAULT_REGION" \
    --output json 2>/dev/null | jq -r '.policyEngineArn // empty' || true)

if [ -z "$ENGINE_ARN" ]; then
    echo "Policy engine may already exist. Attempting to retrieve ARN..."
    ENGINE_ARN=$(agentcore policy get-engine \
        --name "$ENGINE_NAME" \
        --region "$DEFAULT_REGION" \
        --output json 2>/dev/null | jq -r '.policyEngineArn // empty' || true)
fi

if [ -z "$ENGINE_ARN" ]; then
    echo "Error: Failed to create or retrieve policy engine"
    exit 1
fi

echo "✓ Policy Engine ARN: $ENGINE_ARN"

echo ""
echo "=== Step 2: Adding Cedar Policies ==="
echo ""

# Add policies to engine
agentcore policy add-policy \
    --engine "$ENGINE_NAME" \
    --policy-file "$POLICY_FILE" \
    --region "$DEFAULT_REGION" || {
    echo "Policies may already exist. Attempting to update..."
    agentcore policy update-policy \
        --engine "$ENGINE_NAME" \
        --policy-file "$POLICY_FILE" \
        --region "$DEFAULT_REGION" || true
}

echo "✓ Policies added/updated successfully"

echo ""
echo "=== Step 3: Configuring CloudWatch Logging ==="
echo ""

# Configure CloudWatch logging (optional, may fail if not supported)
agentcore policy configure-logging \
    --engine "$ENGINE_NAME" \
    --log-group "$LOG_GROUP" \
    --region "$DEFAULT_REGION" 2>/dev/null || {
    echo "Note: CloudWatch logging configuration may require manual setup"
}

echo ""
echo "=== Step 4: Verifying Policy Engine ==="
echo ""

# Verify the policy engine
agentcore policy describe-engine \
    --name "$ENGINE_NAME" \
    --region "$DEFAULT_REGION" || true

echo ""
echo "=== Step 5: Generating Environment File ==="
echo ""

# Generate environment file
ENV_FILE="$PROJECT_ROOT/.env.policy"
cat > "$ENV_FILE" << EOF
# AgentCore Policy Engine Configuration
# Generated by setup_policy_engine.sh

POLICY_ENGINE_ARN=$ENGINE_ARN
POLICY_ENGINE_NAME=$ENGINE_NAME
EOF

if [ -n "$GOVERNANCE_GATEWAY_ARN" ]; then
    echo "GOVERNANCE_GATEWAY_ARN=$GOVERNANCE_GATEWAY_ARN" >> "$ENV_FILE"
fi

echo "✓ Environment file generated: $ENV_FILE"

echo ""
echo "=============================================="
echo "Policy Engine Setup Complete!"
echo "=============================================="
echo ""
echo "Policy Engine ARN: $ENGINE_ARN"
echo ""
echo "Next steps:"
echo "1. Associate the policy engine with your Gateway"
echo "2. Configure identity provider for user authentication"
echo "3. Test policy evaluation with sample requests"
echo ""
echo "To associate with Gateway:"
echo "  agentcore gateway update \\"
echo "    --name governance-gateway \\"
echo "    --policy-engine $ENGINE_NAME"
echo ""
