import { format } from 'date-fns'

/**
 * Export data to CSV format and trigger download
 */
export function exportToCSV<T extends object>(
  data: T[],
  filename: string
): void {
  if (!data || data.length === 0) {
    console.warn('No data to export')
    return
  }

  // Get headers from first object
  const headers = Object.keys(data[0])

  // Build CSV content
  const csvContent = [
    // Header row
    headers.join(','),
    // Data rows
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = (row as Record<string, unknown>)[header]
          // Handle different value types
          if (value === null || value === undefined) {
            return ''
          }
          if (typeof value === 'string') {
            // Escape quotes and wrap in quotes if contains comma or newline
            const escaped = value.replace(/"/g, '""')
            return escaped.includes(',') || escaped.includes('\n')
              ? `"${escaped}"`
              : escaped
          }
          if (typeof value === 'object') {
            return `"${JSON.stringify(value).replace(/"/g, '""')}"`
          }
          return String(value)
        })
        .join(',')
    ),
  ].join('\n')

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${filename}_${format(new Date(), 'yyyy-MM-dd_HHmmss')}.csv`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export dashboard data to PDF format
 * Note: This is a simplified implementation. For production, consider using
 * libraries like jsPDF, html2canvas, or a server-side PDF generation service.
 */
export function exportToPDF(
  reportName: string,
  data: Record<string, unknown>
): void {
  // Create a printable HTML document
  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    console.error('Could not open print window')
    return
  }

  const timestamp = format(new Date(), 'MMMM d, yyyy HH:mm')

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${reportName} - ${timestamp}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
          color: #1a1a1a;
        }
        h1 {
          color: #0f172a;
          border-bottom: 2px solid #e2e8f0;
          padding-bottom: 10px;
        }
        h2 {
          color: #334155;
          margin-top: 30px;
        }
        .timestamp {
          color: #64748b;
          font-size: 14px;
          margin-bottom: 30px;
        }
        .kpi-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 20px;
          margin: 20px 0;
        }
        .kpi-card {
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 16px;
        }
        .kpi-title {
          font-size: 12px;
          color: #64748b;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .kpi-value {
          font-size: 28px;
          font-weight: bold;
          color: #0f172a;
          margin: 8px 0;
        }
        .kpi-trend {
          font-size: 12px;
        }
        .trend-up { color: #22c55e; }
        .trend-down { color: #ef4444; }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        th, td {
          border: 1px solid #e2e8f0;
          padding: 10px;
          text-align: left;
        }
        th {
          background: #f8fafc;
          font-weight: 600;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e2e8f0;
          font-size: 12px;
          color: #64748b;
        }
        @media print {
          body { padding: 20px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <h1>Data Governance Dashboard Report</h1>
      <p class="timestamp">Generated on ${timestamp}</p>
      
      ${renderKPIs(data.kpis as Record<string, unknown>)}
      ${renderIssuesSummary(data.issuesBySeverity as Array<Record<string, unknown>>)}
      
      <div class="footer">
        <p>This report was automatically generated by the Data Governance Platform.</p>
        <p>For questions or concerns, please contact your data governance team.</p>
      </div>
      
      <script>
        window.onload = function() {
          window.print();
        }
      </script>
    </body>
    </html>
  `

  printWindow.document.write(htmlContent)
  printWindow.document.close()
}

function renderKPIs(kpis?: Record<string, unknown>): string {
  if (!kpis) return ''

  const formatTrend = (trend: number) => {
    if (trend === 0) return '<span>No change</span>'
    const className = trend > 0 ? 'trend-up' : 'trend-down'
    const sign = trend > 0 ? '+' : ''
    return `<span class="${className}">${sign}${trend}%</span>`
  }

  return `
    <h2>Key Performance Indicators</h2>
    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-title">Compliance Score</div>
        <div class="kpi-value">${kpis.complianceScore ?? 0}%</div>
        <div class="kpi-trend">${formatTrend(Number(kpis.complianceScoreTrend ?? 0))} vs last period</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-title">Active Cycles</div>
        <div class="kpi-value">${kpis.activeCycles ?? 0}</div>
        <div class="kpi-trend">${formatTrend(Number(kpis.activeCyclesTrend ?? 0))} vs last period</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-title">Open Issues</div>
        <div class="kpi-value">${kpis.openIssues ?? 0}</div>
        <div class="kpi-trend">${formatTrend(Number(kpis.openIssuesTrend ?? 0))} vs last period</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-title">Pending Approvals</div>
        <div class="kpi-value">${kpis.pendingApprovals ?? 0}</div>
        <div class="kpi-trend">${formatTrend(Number(kpis.pendingApprovalsTrend ?? 0))} vs last period</div>
      </div>
    </div>
  `
}

function renderIssuesSummary(issues?: Array<Record<string, unknown>>): string {
  if (!issues || issues.length === 0) return ''

  const rows = issues
    .map(
      (issue) => `
      <tr>
        <td style="text-transform: capitalize;">${issue.severity}</td>
        <td>${issue.count}</td>
        <td>${Number(issue.trend) > 0 ? '+' : ''}${issue.trend}</td>
      </tr>
    `
    )
    .join('')

  return `
    <h2>Issues by Severity</h2>
    <table>
      <thead>
        <tr>
          <th>Severity</th>
          <th>Count</th>
          <th>Trend</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>
  `
}
